baseurl = "/mongo-spark/1.0-SNAPSHOT"
languageCode = "en-us"
title = "Mongo Spark"
theme = "mongodb"
canonifyurls = false

[blackfriday]
  plainIdAnchors = true


# Update versions in mongodb.toml as well
[[menu.main]]
    name = "API Documentation"
    pre = "<i class='fa fa-file-text-o'></i>"
    weight = 90
    identifier = "apiDocs"
    url = "http://api.mongodb.org/mongo-spark/1.0-SNAPSHOT"

[[menu.main]]
    name = "Source Code"
    pre = "<i class='fa fa-github'></i>"
    weight = 90
    identifier = "githubLink"
    url = "https://github.com/mongodbinc-interns/mongo-spark/tree/master"
